# Generated by Django 2.2.1 on 2020-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
