# Generated by Django 2.2.1 on 2020-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0002_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('signup_confirmation', models.IntegerField()),
                ('user_id', models.IntegerField(unique=True)),
                ('is_compamy', models.IntegerField()),
                ('is_customer', models.IntegerField()),
            ],
            options={
                'db_table': 'accounts_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
